using System;
namespace Scryber.OpenType.Woff2
{
    public enum KnownTableIndex : int
    {
        Cmap = 0,
        Head = 1,
        HHead = 2,
        HMtx = 3,
        MaxP = 4,
        Name = 5,
        OS2 = 6,
        Post = 7,
        Cvt = 8,
        Fpgm = 9,
        Glyf = 10,
        Loca = 11,
        Prep = 12,
        CFF = 13,
        Vorg = 14,
        EBDT = 15,
        EBLC = 16,
        Gasp = 17,
        HDmx = 18,
        Kern = 19,
        LTSH = 20,
        PCLT = 21,
        VDmx = 22,
        VHea = 23,
        VMtx = 24,
        BASE = 25,
        GDEF = 26,
        GPos = 27,
        GSub = 28,
        EBSC = 29,
        JSTF = 30,
        MATH = 31,
        CBDT = 32,
        CBLC = 33,
        COLR = 34,
        CPAL = 35,
        SVG_ = 36,
        sbix = 37,
        acnt = 38,
        avar = 39,
        bdat = 40,
        bloc = 41,
        bsln = 42,
        cvar = 43,
        fdsc = 44,
        feat = 45,
        fmtx = 46,
        fvar = 47,
        gvar = 48,
        hsty = 49,
        just = 50,
        lcar = 51,
        mort = 52,
        morx = 53,
        opbd = 54,
        prop = 55,
        trak = 56,
        Zapf = 57,
        Silf = 58,
        Glat = 59,
        Gloc = 60,
        Feat = 61,
        Sill = 62,
        UNKN = 63
    }
}
